### ISSUE TITLE
Module 3 Exercise 3 Task 1 Step 7

### ISSUE THREAD

**Issue by ramsamdam** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#101]
Hi Please Edit,
Module 3, Exercise 3 , Task 1 , Step 7
as in the new solution app settings element is not on line 14.

**Comment by nicolasploquin** [comment]
Pull request opened to fix this
[https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/pull/95](https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/pull/95)

Line 8 is the correct line

**Comment by seesharprun** [comment]
Pull request accepted
