### ISSUE TITLE
Changes in Instructions

### ISSUE THREAD

**Issue by ramsamdam** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#122]
Hi, Please check the following errors i have come across while executing 532 manual in the instructions, I have only referred to the Answer Key Instructions while executing.
## 1. https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/blob/c-release/Instructions/Labs/dotnet/Mod03/20532C_LAB_AK_03.md#task-1-create-a-web-app-instance-by-using-the-portal

Step 11(n) There is no Step mentioned to Select the pricing tier of SQL Database
After Step n the following steps must be added
o. Select the Pricing tier option.
p. In the Pricing Tier blade, click the View All Link
q. Locate and select the Free pricing tier.
r. Click the Select button.
## 2. https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/blob/c-release/Instructions/Labs/dotnet/Mod02/20532C_LAB_AK_02.md#task-2-create-a-virtual-machine

Step 5. Compute Blade instead of Virtual Machine Blade
## 3. https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/blob/c-release/Instructions/Labs/dotnet/Mod07/20532C_LAB_AK_07.md#task-3-download-documents-from-a-protected-container-by-using-the-sas-token

Step 9 has to be deleted as we are not using Starting/Using Storage Emulator in this Module
## 4. https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/blob/c-release/Instructions/Labs/dotnet/Mod09/20532C_LAB_AK_09.md#task-2-authenticate-to-azure-resource-manager-using-powershell

Note After Step 3 Set-AzureRmContext Command should be used
## 5. https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/blob/c-release/Instructions/Labs/dotnet/Mod10/20532C_LAB_AK_10.md#task-1-create-a-new-management-web-application-by-using-azure-ad-as-the-identity-provider

Step 16 e
More Details can be mentioned as earlier we are referring connection string as just the value after _connectionString="_ whereas here we have to copy the complete string with <connectionString> </connectionString> opening and closing brackets

**Comment by seesharprun** [comment]
Thanks for reporting these bugs. I am reviewing them now and will propose a Pull Request with potential solutions.

**Comment by seesharprun** [comment]
Regarding your *4th* bug, I wonder if we should have the student use the ``Set-AzureRmContext`` command. At the time when labs are written, we don't know the name for their subscription that they are using (Azure Pass). We do know that they should be using an Azure Pass subscription.

Would a note saying "if you have multiple subscriptions, use Set-AzureRmContext" work here? Is there an advantage to using Set-AzureRmContext over ``Select-AzureRmSubscription``?

**Comment by PeterKessler** [comment]
As this would be something that could happen to developers quite often (as they might do some playing around in the MSDN azure subscription and other stuff in the Company azure subscription) and we do not know in the classroom if People really use the Azure pass and not MSDN etc., we should at least mention it. Is this covered in the slides/Manual? If not we even should add a small Explanation here.

**Comment by seesharprun** [comment]
I definitely can see both of your points. I'll open a branch and PR tomorrow

**Comment by seesharprun** [comment]
I have opened a new branch and pull request. This branch can be used to monitor progress on these items.

Pull Request #126
