### ISSUE TITLE
Azure 20532 overview diagram 

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#123]
Do you have a diagram with a visual overview of the Contoso Web application? Student are missing an overview:
•         where do we start (on-premises)
•         for each module: on-premises at start, what’s in the cloud
•         where do we start and where do we end
•         what Azure feature did we implement in which module

Not all students are developers, but also architects and IT pro's preparing for the Azuer exams. Those student are missing that overview.
For example in module 3 we deploy our website in Azure and in module 4 we migrate our data into a SQL Database. However in module 8 we implement the Azure Service Bus and both the database and the website  are both local again.

**Comment by seesharprun** [comment]
This is a great idea!

Some questions before I get started and create a GitHub project:

- How should we source-control the diagram? I imagine this will change as the course evolves. Should we store a binary file (Visio) or store it in a data format (xml, JSON, YAML)?
- Would an overview Markdown file work for this with a rendering of the diagram and breakdown of the labs?
- What else would you want in an overview?

**Comment by ConcreteGannet** [comment]
Hi,

Have a look at Evolus Pencil (http://pencil.evolus.vn/Features.html). It's an open source diagramming and wireframing tool that saves to an XML format, so can be put under version control.

Cheers

Paul Foxworthy

**Comment by seesharprun** [comment]
I'm looking at Evolus now. This is promising. If anyone has any other recommendations let me know. I don't want to "take over" and make the call here if the community think there is an ideal solution.

**Comment by seesharprun** [comment]
I wasn't able to figure out Evolus but I did create an PlantUML implementation for Azure. It's about 2-3 weeks from being completed but this will allow us to generate diagrams:

https://github.com/seesharprun/AZURE-PlantUML

The one glaring weakness is that it requires you to have [GraphViz](http://www.graphviz.org/) installed on your local machine. I could not find a way around this requirement.
