### ISSUE TITLE
Contoso.Events Application in ASP.NET Core

### ISSUE THREAD

**Issue by seesharprun** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#127]
We should take the demo application and do a full implementation in ASP.NET Core.

**Comment by seesharprun** [comment]
This shouldn't take too long to implement. Once it's ready, I am looking for a MCT volunteer who wants to review the ASP.NET Core prototype. You can see if the application will work for your Linux/OSX students.

**Comment by davsebamse** [comment]
I am willing to test on linux if you still need to find someone to do that.

**Comment by seesharprun** [comment]
Cancelled
