### ISSUE TITLE
HTML Version of Build Files

### ISSUE THREAD

**Issue by seesharprun** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#132]
Pull Request #130 recommends that we provide an HTML version of each Markdown file.

I personally believe this is a job for the build engine but i'm open to suggestions. Right now the NPM build script outputs a set of DOCX files. Would it be useful if it built a set of HTML files too?

**Comment by ElaMark** [comment]
I'm confused, why bother? To complete this course students need Internet access, so just refer them to the pages on GitHub when doing exercises etc. Less files=better.

**Comment by seesharprun** [comment]
@ElaMark: There was a lot of rich discussion around this in PR #149. I asked that everyone bring that conversation over here so we can discuss.

Right now the **gh-pages** branch serves as the HTML version of the instructions. This was actually created for another project and worked out as a coincidence.
