### ISSUE TITLE
Update Module 10 for AAD Preview in New Portal

### ISSUE THREAD

**Issue by ramsamdam** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#135]
After the release of AAD Preview in New Portal, can we try to convert Module 10 execution through New Portal as only in this Module we are using the Classic Portal to create AAD.

**Comment by seesharprun** [comment]
This is a great idea! Let's create a branch and PR for this:

PR #136

**Comment by seesharprun** [comment]
This will be done in the next update.
