### ISSUE TITLE
Module 10 no trust Self-Signed Certificate

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#147]
For some students the self-signed certificate dialog doesn't appear and the webpage doesn't display anything.

Exercise 3:
Task 2: Verify that the Management web application requires a sign-in by using an organizational account
    1. In the Solution Explorer pane, right-click the Contoso.Events.Management project, and then click Set as Startup Project.

On the Debug menu, click Start Debugging.
    a. The Microsoft Visual Studio dialog will appear indicating that you can configure IIS Express to trust the self-signed certificate.
b. Click Yes.
c. The Security Warning dialog will appear indicating that the self-signed certificate cannot be verified but can still be installed.
d. Click Yes.

**Comment by denschork** [comment]
I get an error page right away.
"Make sure the web address https://localhost:44319 is correct"

Lab dies here.

**Comment by denschork** [comment]
What is RC4 Cipher? Not supported in IE 11 or Edge anymore????

**Comment by seesharprun** [comment]
@denschork I was not able to find the text:

> "Make sure the web address https://localhost:44319 is correct"

in the Module 10 lab files. Can you give me a specific step number so I can work on resolving this as quickly as possible?

**Comment by denschork** [comment]
Task 2. Verify the management web app requires a sign-in by organizational account.....
step:
1. Set the startup project. DONE
2. Start Debugging.
  a. Studio dialog will appear indicating... IT DOES NOT
  b. ..
  c. Security warning dialog will appear.... IT DOES NOT APPEAR

When START DEBUG it shows error page 
MAKE SURE THE WEB ADDRESS https://localhost:44319 is correct

Lab dies right there.

**Comment by seesharprun** [comment]
@denschork This helps a lot! I will begin investigating this and issue a correction for those instructions. 

Estimated response is 2-3 business days as there are a few of us offsite at a MCT related summit.

**Comment by denschork** [comment]
If you use the http://localhost:XXXX url instead manually typing it in, the correct prompts come up. You can go through the AD login. BUT you still end up with the same error page at the end. Details recommend enabling TLS/SSL 1.0, 1.1, 2.0.

ending url is the https://localhost:xxxx

**Comment by ConcreteGannet** [comment]
> What is RC4 Cipher? Not supported in IE 11 or Edge anymore????

RC4 is an older encryption algorithm that has been used by Transport Layer Security and Secure Sockets Layer. It is now thought to be insecure, so it is being phased out. You are right that it has been disabled in IE 11 and Edge: https://blogs.windows.com/msedgedev/2016/08/09/rc4-now-deprecated/ .

You might need to regenerate the certificate so the site works with newer browsers.

**Comment by ramsamdam** [comment]
I am getting the same error, as we are deploying the VM with pre installed versions of Browsers/SDKs/VS do we need to go and explicitly update anything to overcome this error?

**Comment by ConcreteGannet** [comment]
This: https://forums.iis.net/t/1230477.aspx?Windows+10+Pro+Visual+Studio+Enterprise+2015+fails+on+IIS+Express+using+HTTPS+SSL+web

suggests repairing IIS Express, which might upgrade it to a newer version.

**Comment by ramsamdam** [comment]
@ConcreteGannet  Thanks a lot, error got resolved after repairing IIS Express

**Comment by ConcreteGannet** [comment]
Good news.

Could you add that step to the lab instructions?

**Comment by ramsamdam** [comment]
Solution:
1.	Close Internet Explorer if you face "Make sure the web address https://localhost:44319 is correct"
Error and Minimize Visual Studio.

2.	Press Windows + R, Type Control Panel and Press Enter.
 
3.	In Search Control Panel, type Program Features and Reference and Click on it.
 
4.	Locate IIS Express 10.0, right-click on it and click on Repair.
 
5.	Continue your execution from Task 3.

**Comment by NerdOwls** [comment]
I had the same issue while on the course, ramsamdam's steps above rectified it.

**Comment by seesharprun** [comment]
I'm actively looking at this individual lab and started working on rewriting it so that we can avoid re-installing IIS.


________________________________

**Comment by denschork** [comment]
Thanks again. Repairing IIS works perfectly for he lab as written.
