### ISSUE TITLE
Lab 07 - Storing Generated Documents in Azure Storage

### ISSUE THREAD

**Issue by denschork** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#150]
SO WHERE is the sign-in button on the HOME page ?
End of Exercise 3 - Task 3 - step 26:
 Click the Sign-in-Sheet button for any event.

So where is the button? Lab dies right here without the button.

Also, there is no blob container sign-in when using Cloud Explorer in next Exer 4 Task 1 step 7.

**Comment by denschork** [comment]
Thanks. I missed it. 
Multi-project startup.  
Should be a note that it comes up in the background underneath the Contoso.Events.Web home page. For the SLOW students and trainers.......
Thanks.

**Comment by seesharprun** [comment]
@denschork Does it come up in the background or as a new tab for you?

**Comment by denschork** [comment]
Separate browser window using IE 11. Its easy to miss.

**Comment by denschork** [comment]
Separate browser window.
