### ISSUE TITLE
Mod2 VM Template 

### ISSUE THREAD

**Issue by ramsamdam** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#153]
https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/blob/c-release/Instructions/Labs/dotnet/Mod02/20532C_LAB_AK_02.md#task-2-create-a-virtual-machine

Visual Studio Community 2015 with Azure SDK 2.9 on Windows Server 2012 R2 is no longer available, we must now use the following version and update the instructions

Visual Studio Community 2015 Update 3 with Azure SDK 2.9 on Windows Server 2012 R2

**Comment by ConcreteGannet** [comment]
Thanks @ramsamdam . Can you make a patch for that?

**Comment by seesharprun** [comment]
I have patched the ARM template but haven't done the instructions yet due to a US holiday. Will get to that as soon as I am able


________________________________
