### ISSUE TITLE
Microsoft.Insights/components location change

### ISSUE THREAD

**Issue by jeremyhofman** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#155]
In the azuredeploy.json file referenced in the xPlat CLI lab, Central US is referenced for the Application Insights components type.  This leads to an error in when the New-AzureRmResourceGroupDeployment cmdlet is run with a code of "MissingRegistrationForLocation".

Updating the location to "East US" in the template resolves the issue.

**Comment by seesharprun** [comment]
I wonder if this is a subscription or regional issue. If we hard-code a location, I would recommend the West US region.

I am thinking an evaluation is in order and then I can open a PR

**Comment by jeremyhofman** [comment]
I just gave West US a try, no go.  Looks like the GA announcement for Application Insights a few weeks ago touched on this breaking change.

https://azure.microsoft.com/en-us/updates/application-insights-general-availability-in-additional-regions-and-resource-location-update-east-us-south-central-us-west-europe-and-north-europe/

**Comment by seesharprun** [comment]
I dread hard-coding a location but you are correct.


________________________________

**Comment by seesharprun** [comment]
This will be validated with the next release of the course.
