### ISSUE TITLE
demo05 Visual Studio

### ISSUE THREAD

**Issue by ramsamdam** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#156]
I am unable to find any options as per the visual studio instructions in demo06

**Comment by ConcreteGannet** [comment]
Which exercise? Which step?

Thanks.

**Comment by ramsamdam** [comment]
https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/blob/c-release/Instructions/Demos/dotnet/Mod05/20532C_DEMO_05-monitoring_a_web_application.md - demo-monitoring-a-web-application
