### ISSUE TITLE
mct_guide.md

### ISSUE THREAD

**Issue by faludigabor** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#158]
There is no longer a Powershell script in the repository. 

**Plus pandoc-bin will not install on windows .** Neither on Linux. 

Needs a fix. 

 this ok? (yes) 
falu@debgui1:~/test1$ npm install --save pandoc-bin
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated find-file@0.1.4: Use the globby package instead

> pandoc-bin@0.1.2 postinstall /home/falu/test1/node_modules/pandoc-bin
> node index.js

Linux:  
⧗ Downloading Pandoc (~20-50MB depending on OS). This may take a minute or so.
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { url: 'https://raw.github.com/toshgoodson/pandoc-bin/0.1.0/vendor/linux/x64/pandoc',
  name: 'pandoc',
  os: 'linux',
  arch: 'x64' }
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at /home/falu/test1/node_modules/download/index.js:35:43
    at each (/home/falu/test1/node_modules/each-async/each-async.js:63:4)
    at module.exports (/home/falu/test1/node_modules/download/index.js:33:5)
    at /home/falu/test1/node_modules/bin-wrapper/index.js:108:20
    at /home/falu/test1/node_modules/bin-wrapper/index.js:141:24
    at /home/falu/test1/node_modules/bin-check/index.js:30:20
    at /home/falu/test1/node_modules/executable/index.js:39:20
    at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN test1@1.0.0 No description
npm WARN test1@1.0.0 No repository field.

**--- Windows**

Downloading Pandoc (~20-50MB depending on OS). This may take a minute or so.
th.js:7
  throw new TypeError('Path must be a string. Received ' + inspect(path));
  ^

peError: Path must be a string. Received { url: 'https://raw.github.com/toshgoodson/pandoc-bin/0.1.0/vendor/win/pand
xe',
name: 'pandoc.exe',
os: 'win32' }
  at assertPath (path.js:7:11)
  at Object.basename (path.js:799:5)
  at S:\Falu\workspace\c#\20532\20532-DevelopingMicrosoftAzureSolutions\Build\node_modules\download\index.js:35:43
  at each (S:\Falu\workspace\c#\20532\20532-DevelopingMicrosoftAzureSolutions\Build\node_modules\each-async\each-asy
s:63:4)
  at module.exports (S:\Falu\workspace\c#\20532\20532-DevelopingMicrosoftAzureSolutions\Build\node_modules\download\
x.js:33:5)
  at S:\Falu\workspace\c#\20532\20532-DevelopingMicrosoftAzureSolutions\Build\node_modules\bin-wrapper\index.js:108:
  at S:\Falu\workspace\c#\20532\20532-DevelopingMicrosoftAzureSolutions\Build\node_modules\bin-wrapper\index.js:141:
  at S:\Falu\workspace\c#\20532\20532-DevelopingMicrosoftAzureSolutions\Build\node_modules\bin-check\index.js:30:20
  at S:\Falu\workspace\c#\20532\20532-DevelopingMicrosoftAzureSolutions\Build\node_modules\executable\index.js:39:20
  at FSReqWrap.oncomplete (fs.js:123:15)
m ERR! Windows_NT 10.0.14393
m ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i
ll" "--save" "pandoc-bin"

**Comment by seesharprun** [comment]
Both the PowerShell script (old) and NPM script (current) use Pandoc in some way. Can you give me any more information about your Windows environment? Just tried `npm install` on a fresh machine with latest NPM installed and it worked.

**Comment by faludigabor** [comment]
Hey, 

Yes indeed , both linux and windows fails to install when running npm install. 

This is what I did in the linux vm , to reproduce the issue :

1. do npm init in an empty folder.
2. npm install --save **pandoc-bin**

You will see the error .

I just tried on my windows v6.9.3  - stable , npm 3.10.10
on my debian vm : 
node  : v6.8,1
npm  v3.10.8

**Comment by seesharprun** [comment]
Thanks, I will use this information to look into the issue and reproduce.

**Comment by seesharprun** [comment]
Looks like it's a known issue so I may have to work on a contingency plan:

https://github.com/toshgoodson/pandoc-bin/issues/2

**Comment by seesharprun** [comment]
I was able to resolve by updating the pandoc version in the **package.json** file and updating NPM to v5.x.

The only thing I can commit to the repo is an updated **package.json** file with the new **pandoc-bin** package version.

I have also updated the MCT Guide to recommend downloading the pre-compiled Word files instead of manually building them.
