### ISSUE TITLE
Lab 7 - Exercise 4 - Task 1 - Cannot change the signin container’s public access.

### ISSUE THREAD

**Issue by Hector47** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#160]
In the Lab 7, Exercise 4, Task 1, Step 4, the instruction is 

> 4.	Change the signin container’s public access to Off.

This option called "Public Read Access" is read only in the Cloud Explorer.

In the AK file the instruction is correct: 

> 9.Ensure that the value of the Public Read Access property is set to Off.

**Comment by seesharprun** [comment]
Fixed

**Comment by seesharprun** [comment]
You should see the fix in version 1.1.1
