### ISSUE TITLE
Lab 10: Ex 3: Change Authentication fails

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#161]
Lab 10: Ex 3: Task 1: Step 7: After updating the temporary password and trying to sign in as admin@ad20532[Your Name].onmicrosoft.com an error window is displayed: 
"User credential verification failed"
 "Error: The user account doesn't have the required permission to access the domain"

Verified that the username and new password (Pa$$w0rd) is correct by logging into http://myapps.microsoft.com successfully with new password. This issue was reported first by a student and I have successfully recreated in my own lab to verify. Cannot continue lab. See attached screenshot.

![lab10-error-recreated1](https://cloud.githubusercontent.com/assets/22414394/24579991/73eb2c56-16ce-11e7-9e44-cdad6f3e9ea8.png)

**Comment by seesharprun** [comment]
Looking into this immediately to determine the cause of the bug.

**Comment by begler1** [comment]
I've recreated this with VS 2015 with or without Update 3.

**Comment by molenaar** [comment]
After repairing IIS 10.0 Express and rebuilding the Event Management project on Visual Studio 2017, a popup appears to trust the SSL certificate. Then, login with standard user, change the password and click the accept button. Now, it succesfully redirects to the Events Administration website.

Repairing IIS Express:
https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/issues/147

**Comment by begler1** [comment]
So we need to use Visual Studio 2017 moving forward? This will require all labs to be retested and lab instructions/code verified, correct?

**Comment by davsebamse** [comment]
If the box which should ask about ssl do not pop up the following snippet can be used to allow self signed certificates:
```
cd C:\Program Files (x86)\IIS Express
IisExpressAdminCmd.exe setupsslUrl -url:https://localhost:44387/ -UseSelfSigned
```
From this answer on StackOverflow: http://stackoverflow.com/a/38220369

**Comment by begler1** [comment]
I have verified that this issue is resolved using Visual Studio 2017.

**Comment by davsebamse** [comment]
@begler1: did you use the azure image?

**Comment by begler1** [comment]
Correct. I used the following Azure Image: "Visual Studio Community 2017 on Windows Server 2016 (x64)"
