### ISSUE TITLE
Module 2 Exercise 3 Task 2: Install Visual Studio 2015 Community Edition

### ISSUE THREAD

**Issue by microsmith** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#17]
Module 2 Exercise 3 Task 2: Install Visual Studio 2015 Community Edition
http://go.microsoft.com/fwlink/?LinkID=524433.
This URL returns "vs_community_exe couldn't be downloaded."

Also, step 5 refers to vs_ultimate_exe.

Several places Task 2 refers to the Community Edition and then the Ultimate Edition. Which should be installed?

The remaining steps are not 100% correct.

**Comment by ConcreteGannet** [comment]
I downloaded Studio 2015 Community instead from https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx . Worked fine for me.

**Comment by mwasham** [comment]
fixed link
