### ISSUE TITLE
20532C_LAB_AK_08 text incorrect

### ISSUE THREAD

**Issue by dtlne** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#170]
Excercise 2.5.33 refers to a try-catch block that is no longer present in the indicated location (Contoso.Events.Worker.ProcessQueueMessage:22-24)
Excercise 3.1.15 contains an instruction to invoke the CreateIfNotExists method on a queue, though no queue is directly referenced in the current task.

**Comment by seesharprun** [comment]
This has been updated in the latest lab instructions.
