### ISSUE TITLE
Lab 10

### ISSUE THREAD

**Issue by andrewbeldean** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#171]
Without upgrading to VS 2017 you cannot complete this lab

**Comment by seesharprun** [comment]
This is a high priority bug!

**Comment by seesharprun** [comment]
It looks like the lab instructions have already been updated to have the student install Visual Studio 2017.

Did you see a place where the student was instructed to install Visual Studio 2015? If you have, please re-open the issue so I can track it down and fix it.
