### ISSUE TITLE
DOCX versions of the files

### ISSUE THREAD

**Issue by microsmith** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#172]
Curious as to why simple DOCX or PDF versions of the lab files are not available here. The download of the .md files and then running a "build script" is not the most intuitive process for easy distribution of updates, especially with all of the other tools that need to be downloaded first. 

Each time I download one of the open source tools, it seems that there's another open source thingy that needs to be downloaded to make it run. So far I cannot even get the GitHub Windows Desktop tool to run. (Could be Windows 10 issues.)

Can a "build" process be part of the release of updated content?

**Comment by microsmith** [comment]
Just found them!

https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/releases/tag/C-v1.0.6

In the lab_instructions-v1.0.6.zip file!

Maybe you should add a big note on the home page so MCTs can just download the updated files in one or two clicks. At least rename lab_instructions-v1.0.6.zip to something like lab_instructions-v1.0.6-WordFormat.zip

Looks like all we need are the following two files, out of the hundreds on the GitHub site.
allfiles-v1.0.6.zip 
lab_instructions-v1.0.6.zip

Are there any other files we need from the GitHub site to run the most up to date version of the class? The last release is from December, and in Azure, five months is a lot changes.

**Comment by microsmith** [comment]
Ok, I just found "Download Latest Student Handbook and AllFiles Content" on the home page. I first followed the link just above that one "Are you a MCT? - Have a look at our GitHub User Guide for MCTs" where it says "If you want to build Word documents from Markdown files, you **must** clone or fetch a copy of the repo on your local computer. " and wasted four hours with GitHub Desktop, PanDoc and PowerShell scripts.

**Comment by seesharprun** [comment]
You are right. We can definitely improve the documentation to make it clearer on downloading the latest build assets.

We are doing a sequence of bug fixes now and will update the docs as part of this task.

**Comment by microsmith** [comment]
Sidney,

Thanks!

When will the bug fixes be available? My next 20532 is next week.

Mike

**Comment by seesharprun** [comment]
I don't want to mislead here and promise it will be ready by next week. I expect the next round of bug fixes to be ready by the end of June.

As always, validate the labs so you won't have any in-class surprises.

**Comment by seesharprun** [comment]
I updated the landing page to show the link to download AllFiles content as the first link.

Would this work for you? If not, please re-open the issue.
