### ISSUE TITLE
Visual Studio Community 2017 - extended trial expired

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#178]
Lab 2 Task 2 Step 5:
Using image for "Visual Studio Community 2017 on Windows Server 2016 (x64)" shows error after launching VS 2017 for first time later in lab:
Error: "Your extended trial has expired. License with an online account or a product key"
Tried "Check for an updated license" and "Unlock with a Product Key" and tried different subscription but only option then is to "Exit Visual Studio".

**Comment by seesharprun** [comment]
Can you share a screenshot?

**Comment by begler1** [comment]
Tested with the "Visual Studio Community 2017 on Windows Server 2016 (x64)" image and error does not occur. Also tested with "Visual Studio Enterprise 2017 on Windows Server 2016 (x64)" and error occurs. Must have selected incorrect image. Please close this issue.
