### ISSUE TITLE
Update to the 20532C

### ISSUE THREAD

**Issue by andrewbeldean** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#179]
Anyone have an idea if Microsoft are updating the 20532 to a D version same as 20533?

Cheers

**Comment by PeterKessler** [comment]
Yes they plan to update it. Should be released around Feb 2018.

**Comment by seesharprun** [comment]
Yep, we are working on an update to the material first. You should start seeing lab changes around the holidays in the [d-release](/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/tree/d-release) branch.

**Comment by seesharprun** [comment]
I'm leaving this issue open for any discussion on 20532D

**Comment by molenaar** [comment]
Keep us posted! Very interested and looking forward to the new version. Asp.net core? Docker? CosmosDB?

**Comment by willywil548** [comment]
Service Bus is in the new portal. Click new and search for Service Bus.

**Comment by seesharprun** [comment]
I would also like to create PDF version of the lab instructions but I haven't found a reliable way to do this with NPM

**Comment by Pablites** [comment]
I will try to modify instruction in module 10 today and remove all references to Azure Classic Portal and make pull request.
