### ISSUE TITLE
20532B_LAB_AK_03.md

### ISSUE THREAD

**Issue by microsmith** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#18]
Assuming you want all of the steps to be up to date...

In 20532B_LAB_AK_03.md:

> In the Database list, select Create a free 20 MB SQL database.
Now says "Create a free SQL database"

> In the navigation page on the left side, click Websites.
In general, "Websites" are now "Web Apps".

> then double-click Contoso.Events.sln
The default install of Windows does not display file extensions. 
Error message: project requires SQL Server 2012 Express LocalDB, which is not installed on this computer

> On the Debug menu, click Start Debugging.   (two places in the lab)
Due to the missing SQL Server, the app will fail: ProviderIncompatibleException.
(Maybe change the Start Debugging to just a Build.)

**Comment by bobleith** [comment]
Got the local app to work by separately downloading/installing SQL Server 2014 Express with Tools with defaults (instance name SQLExpress) and changed the connection string to .\SQLExpress.

**Comment by mwasham** [comment]
instructions for install added
