### ISSUE TITLE
Lab 10 Ex 3 Task 14 Step a. (Important!) Package Manager Console

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#181]
Lab 10 Ex 3 Task 14 Step a. (Important!) Package Manager Console
If you do not see the Default Project List, you can Auto Hide the Solution Explorer and Properties sheet to expand the window or click the small ellipsis on the right of the Package Manager Console pane title bar. Then, in the Default Project list, select Contoso.Events.Management. Otherwise the EntityFramework will not install correctly.

**Comment by seesharprun** [comment]
We are in the middle of releasing the newest version of the labs to support 20532D. This change will be made to the 20532D version of the labs instead of the 20532C version. I expect the new version of the course to launch in Feburary or March.
