### ISSUE TITLE
Limitations of Azure Pass Subscription and Free Trial

### ISSUE THREAD

**Issue by tektrainer** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#187]
It would seem that there have been some limitations placed on creating VMs of certain sizes when one is using the Azure Pass or Free Trial subscriptions. I had a student who had both types of subscriptions and I tried to deploy the 20532 vm image to west us, west us 2, central us and south central us and kept getting an error that the vm size was not supported in that region. When I deployed using my msdn subscription in central us I had no issues whatsoever. Through trial and error my students have found the b and ds series seem to work the best.

**Comment by seesharprun** [comment]
I will update the instructions in 20532D to reflect this discovery. Thank you!
