### ISSUE TITLE
Lab 2 Ex 2 Task 1 Step 5c new Storage Account kind options

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#188]
Lab 2 Ex 2 Task 1 Step 5c needs to be changed to the following based on Storage Account kind options:
 	"c. In the Account kind list, ensure that the Storage (general purpose v1) option is selected."

**Comment by seesharprun** [comment]
We are in the middle of releasing the newest version of the labs to support 20532D. This change will be made to the 20532D version of the labs instead of the 20532C version. I expect the new version of the course to launch in Feburary or March.
