### ISSUE TITLE
generate word documents

### ISSUE THREAD

**Issue by chrzanowskiItta** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#190]
Hello How can I generate the labs word document and answer key ?
I use to run pandoc.ps1
Tks

**Comment by seesharprun** [comment]
This course does not have a pandoc.ps1 file in the c-release branch. If you look in the build folder, you should see build instructions using Node.

We are working on updating the course before the end of February to have an automated build process using Docker.

If you just need the lab instructions, you should check out the latest download link in the “releases” folder.

**Comment by seesharprun** [comment]
https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/releases
