### ISSUE TITLE
lab 4

### ISSUE THREAD

**Issue by chrzanowskiItta** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#193]
Hello 
In task 1 step 10
whe have to modify the eventscontext.cs file
static EventsContext(Database.SetInitializer<EventsContext>(new EventsContextInitializer());
VS says that SetInitializer dont exist in database ....
tks

**Comment by ConcreteGannet** [comment]
Hi @chrzanowskiItta . It's in Entity Framework 5 and 6:

https://msdn.microsoft.com/en-us/library/gg679461(v=vs.113).aspx

You might need to do a rebuild to download the NuGet package.
