### ISSUE TITLE
Module 10 - CLASSIC PORTAL NO LONGER EXISTS!

### ISSUE THREAD

**Issue by Misiu** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#196]
In Module 10, on same beginning there is instruction:

> Task 1: Sign in to the Azure Classic Portal

Problem is Classic Portal no longer exists!
Please fix this as soon as possible.

**Comment by tiagocostapt** [comment]
You can read at https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/issues/179 that the team is working in a new course versions that should release soon.

**Comment by Pablites** [comment]
I will try to modify instruction today and make pull request.

**Comment by seesharprun** [comment]
I created a new release (**1.2.1**) based on @Pablites commits and have released it here: https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/releases/tag/C-v.1.2.1

This is going to be the last release for 20532C until we release 20532D towards the end of March.
