### ISSUE TITLE
Lab 4 - Task 5: No data populated on cloud service database

### ISSUE THREAD

**Issue by bobleith** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#20]
I am able to get the data to populate to the local database using the data generation project, but then when publishing to the cloud only the tables are created. It doesn't seem the steps as given in the answer key actually migrate over the data created in the local database or execute the data generation automatically.

**Comment by bobleith** [comment]
I finally got the data uploaded by using SQL data compare against the local database to the database deployed on the cloud and then doing the update target, but it seems there should be an easier way.

**Comment by davsebamse** [comment]
If you follow the guide then the data will be created using the database initializer
