### ISSUE TITLE
Service BUS Mod 8

### ISSUE THREAD

**Issue by chrzanowskiItta** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#200]
hello In lab 8
31.	Double-click the Functions.cs file.
32.	Locate the ProcessQueueMessage method.
33.	Locate the target line of code within the method:
 	HandleMessage(message);
34.	Right-click the target line of code, point to Breakpoint, and click Insert Breakpoint.
35.	On the desktop, click the Home - Contoso.Events.Administration browser window.
36.	On the home page of the Contoso Events Administration web application, click the Events button to go to the list of events.
37.	Click Sign-In Sheet for any event in the list.

**how can can I see the msg in the queue
My student ask me ?????**

**Comment by tiagocostapt** [comment]
Check this project: https://github.com/paolosalvatori/ServiceBusExplorer
