### ISSUE TITLE
20532 version D???

### ISSUE THREAD

**Issue by PeterWallenius** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#201]
I'm delivering 20532 version D right now, but the Allfiles is only version C. 
This means that I do not have any exercise for the new module 10, that is inserted between module 9 and module 10 in version C. When can I expect the github files to be updated?

Best regards

Peter W

**Comment by janssenr** [comment]
+1

**Comment by liketaurus** [comment]
I have this class on this week. And I decide to use an old (20532C v3.2.1) solution files and make some mix from old and new lab instructions...

By the way - slides (from Learning Download Center) and Handbook (both - on Skillpipe and PDF-version from Learning Download Center) are also do not match...

**Comment by seesharprun** [comment]
So after a ton of headache and pain, the bug in the repository has a work-around.

I still can't commit directly to the repository without "unwinding" history again. It's very strange and I have no clue why it's happening after getting expert opinions and trying to fix this issue myself for weeks.

The remaining labs were brought in with Pull Request #208 today.

The latest release of the D Labs are here: <https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/releases/latest>.

The labs are built automatically but you can build it yourself manually if you would like. The instructions are here: <https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/tree/master/.build>.

I hope this gets you unstuck! I apologize again for how long this took, I was under the gun to come up with a solution and the fastest way to get a solution this week was to delete everything and start over.

**Comment by seesharprun** [comment]
I got feedback from multiple people that the Skillpipe and PDF books don't match. I escalated this with people at Microsoft Learning who are directly involved with that and we are waiting for an answer.
