### ISSUE TITLE
20532 D Version - Build script fails

### ISSUE THREAD

**Issue by pdlab** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#207]
Were are all the  allfiles, modules and lab instructions for "D" version?
 I only see 4 modules listed.
lab files are in .md format as well.

This has a "Build" script which fails even with prerequisite software installed.
"npm run build" command fails. This was the command from previous build.
not sure if that's even correct as there are no instructions on how to run current "build" script anymore.

Were can i get everything required for our teach next week?

**Comment by jdevr1es** [comment]
Peter,

I am another MCT teaching 20532 th9is week. Take a look at the next lower thread on the issues page for the status of this problem.
I and another trainer have been using the Version C labs this week, until the issue is resolved.

**Comment by seesharprun** [comment]
So after a ton of headache and pain, the bug in the repository has a work-around.

I still can't commit directly to the repository without "unwinding" history again. It's very strange and I have no clue why it's happening after getting expert opinions and trying to fix this issue myself for weeks.

The remaining labs were brought in with Pull Request #208 today.

The latest release of the D Labs are here: <https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/releases/latest>.

The labs are built automatically but you can build it yourself manually if you would like. The instructions are here: <https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/tree/master/.build>.

I hope this gets you unstuck! I apologize again for how long this took, I was under the gun to come up with a solution and the fastest way to get a solution this week was to delete everything and start over.

**Comment by seesharprun** [comment]
If the build script doesn't work for you, please re-open this issue.

You can also check the latest status of the CI build here: <https://circleci.com/gh/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/tree/master>
