### ISSUE TITLE
Lab4 - command timeout occurs when running in Azure

### ISSUE THREAD

**Issue by alex-randall** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#21]
AUTHOR
Alex Randall, Microsoft employee
Senior Consultant, Modern Apps
I am currently taking the 20538B class this week as a student

SPECIAL THANKS
MJ Parker
Microsoft certified trainer
for being an awesome trainer, coming to a similar conclusion to me in the off hours, and inspiring me to make the fix (pull request coming) web.config based

BACKGROUND:

Summary: 

For Lab04 - It turns out that SQL Azure sometimes takes longer to create the database (for multiple students) than the default ADO.NET command timeout of 30 seconds [https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlcommand.commandtimeout(v=vs.100).aspx](https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlcommand.commandtimeout(v=vs.100).aspx) when running the web app in the browser for the first time in Azure after publishing with the new "seed code" in place.

Details:

Multiple students (including me) had a:

	wait operation timed out

exception with Lab04 after typing in the seed code, publishing to Azure and attempting to run in the browser

After lots of detailed debugging by me (using Intellitrace), found out that the failure was during the create database ADO.NET command (after the drop database, which did execute successfully) issued by entity framework on app start.  The actual failure was an: ADO.NET command timeout.

Also found other people having a similar problem:
[http://stackoverflow.com/questions/32419297/timeout-when-setting-up-entity-framework-connecting-to-azure](http://stackoverflow.com/questions/32419297/timeout-when-setting-up-entity-framework-connecting-to-azure)

Also note: for some people, changing the connection timeout in the Web.config connection string did fix it, however it did not fix it for several students (including me).

NOTE: pull request coming in from that has a fix!  :)

**Comment by alex-randall** [comment]
Seems as I don't have access to submit a pull request. 
Here's a possible commit message for it:

ISSUE #21 FIX: set the command timeout to 180 seconds and made it configurable in Web.config

 I have attached the fixed
[Issue21Fix-UpdatedFilesOnly.zip](https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/files/195928/Issue21Fix-UpdatedFilesOnly.zip)
 files here.

**Comment by alex-randall** [comment]
Forgot to add that the fix: 

1) sets the ADO.NET default command timeout for the database to 180 seconds.
2) reads that setting from a new value in Web.config (so it can be manipulated without having to recompile or republish to Azure.

Thanks!

**Comment by davsebamse** [comment]
Another fix is using 
```CreateDatabaseIfNotExists``` instead of ```DropCreateDatabaseAlways```

**Comment by alex-randall** [comment]
Note, forgot to say, I already tried CreateDatabaseIfNotExists, but the ADO.NET command timeout still happened in my case.  Still feel my previously submitted solution is safer for students having a positive experience with Azure and not having timeout issues with this lab.

**Comment by davsebamse** [comment]
Can you update the instructions? So it will be easier to do a pull request for the maintainer.

**Comment by mwasham** [comment]
updated timeout
