### ISSUE TITLE
Heads-Up: Active Testing

### ISSUE THREAD

**Issue by seesharprun** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#210]
I had to do a full deletion of re-creation of this repository from a historical version to get the D labs fixed.

Because of that, I assume that every lab version is the latest but I cannot be totally sure that every lab has the latest bug fixes. 

Over the next week, I will be making minor bug fixes and changes. You should see a few incremental versions as each bug gets identified and fixed.

**Comment by pdlab** [comment]
Will you be adding the lab instructions to this repository?
Currently all i see are the lab answer files only?

**Comment by seesharprun** [comment]
Yes! We had a bug with the repository where we could not get the files fixed for multiple weeks.

I was able to issue a workaround last week to fix it for the Lab AK files and some of the demos to remove the block for most MCTs.

I am working on fixing the high-level instructions now. 2/11 are in the repo.

**Comment by seesharprun** [comment]
Most of the testing is done. We just pushed a new release with small bug fixes found in testing.

https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/releases/tag/D-v4.0.17

These lab files were sources from a version a few commits before we finished testing. While this testing is redundant, I am glad that we are doing it now.

**Comment by seesharprun** [comment]
I just want to let everyone know that our round of testing has concluded.
