### ISSUE TITLE
Mod 11 Exerc 2 Validate Azure AD Security

### ISSUE THREAD

**Issue by NFGodoy** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#215]
# Module: 11
#### Step: 2

As in the Mod10 we could not get a fully successful deployment, but as the boiler plate original webm was deployed anyway I thought the Authentication/Authorization part could be carried out despite of not really having the Events app content replacing the original web app. 
 So I went ahead into Task 2 and all steps were all fine.
But in Task 3 when I click Browse I just get a page with the content ' You do not have permission to view this directory or page'.

**Comment by seesharprun** [comment]
We resolved the issue in Module 10 and are working to resolve this as quickly as possible. It's a holiday in the US so there's a bit of a delay.

If you don't feel like waiting, you could try this lab again using the latest version of the lab instructions (4.1.25)

**Comment by seesharprun** [comment]
Did you get a chance to try this lab again?

In our testing, we are seeing an intermittent portal error preventing the student from creatjng an Azure AD application.

Even though this is a bug with Azure and not the lab instructions, I don’t want to close this issue util everything is resolved.

**Comment by NFGodoy** [comment]
Not yet. I will try again today or this weekend (Sydney, AU Time). Thanks for such a hard work you are putting on this new release.  
Cheers.
--------------------------------------------
On Fri, 1/6/18, Sidney Andrews <notifications@github.com> wrote:

 Subject: Re: [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions] Mod 11 Exerc 2 Validate Azure AD Security (#215)
 To: "MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions" <20532-DevelopingMicrosoftAzureSolutions@noreply.github.com>
 Cc: "NFGodoy" <nfdegodoy@yahoo.com.au>, "Author" <author@noreply.github.com>
 Received: Friday, 1 June, 2018, 2:01 AM
 
 Did you get a chance to try this
 lab again?
 In our testing, we are seeing an intermittent portal
 error preventing the student from creatjng an Azure AD
 application.
 Even though this is a bug with Azure and not the lab
 instructions, I don’t want to close this issue util
 everything is resolved.
 
 —
 You are
 receiving this because you authored the thread.
 Reply
 to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by ElaMark** [comment]
My students tried it today and none had any success.

**Comment by seesharprun** [comment]
I'm seeing this issue:

![example](https://user-images.githubusercontent.com/5067401/40861044-ab5d3c74-65b5-11e8-8aa4-b3303b649efe.png)

Is this the same issue everyone else is seeing?

**Comment by NFGodoy** [comment]
Hi,
Lab 11 Exerc 2 Task 2 Step 10
Changing "Grant Common Data Services" to "Off"
fixes the issue.

**Comment by seesharprun** [comment]
I will try this out today.

It’s still a bug with the service but this will unblock students.
