### ISSUE TITLE
Instructions (Lab 07, Ex3)

### ISSUE THREAD

**Issue by ElaMark** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#217]
# Module: 07
#### Step: 10

Incorrect return object

I believe the line should read: 

`return new DownloadPayload { Stream = blobStream, ContentType = blob.Properties.ContentType };`

**Comment by seesharprun** [comment]
The bug is fixed in this release or later: https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/releases/tag/D-v4.1.30
