### ISSUE TITLE
Demo for Module5

### ISSUE THREAD

**Issue by dromagnoli77** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#220]
Hi, I download the latest version of the LabInstructions (version 4.1.30), but there is no folder for Module5.
On the MOC there is a demo for Module5.

Thanks

**Comment by Usamawahabkhan** [comment]
their is not Module 5 demo Lab instructions. This course must QA manything are still not working

**Comment by seesharprun** [comment]
Hello. Module 5 has never had any lab instructions. This module is focused on design patterns and did not have a lab in the B, C or D release.
