### ISSUE TITLE
Module 4 Ex 2 Task 2 Step 10: Instructions fail to include using director for Event type.

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#233]
# Module: 04
#### Step: 10

Description of issue
Instructions fail to include using director for Event type. Column EventRegistrationType is not initialized so it defaults to zero. 

Repro steps:

1. Proceed to Ex 2 Task 3 Step 13 to see the value of column EventRegistrationType . It defaults to 0 with the current instructions. Should be set to a value by the code.

**Comment by tiagocostapt** [comment]
EventRegistrationType property is not needed to finish the lab. I did the all lab steps without any issues.
Can you help me and explain why to you need to set a value to the EventRegistrationType  property? 
Thanks!

**Comment by begler1** [comment]
Apologies, I was under the impression that EventRegistrationType was necessary for the application to function correctly.

**Comment by tiagocostapt** [comment]
No problem. I will now close this issue.
