### ISSUE TITLE
Looks like you need an MSDN subscription

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#248]
# Module: 02
#### Step: 05

Description of issue
When selecting any of the Visual Studio Community editions, the portal replies with : Looks like you need an MSDN subscription.

So, how to create a VM with Visual Studio Community Editions installed?

Repro steps:

1.
1.
1.

**Comment by seesharprun** [comment]
Unfortunately, this project is no longer actively maintained.

**Comment by molenaar** [comment]
We found a solution. There are two ways to create a vm with visual studio installed:
1. Create a resource and look for Visual Studio. A new general blade appears with a drop down menu at the bottom where you select the image
2. You can select virtual machines and add a new virtual machine. In the image drop down menu you can search for a visual studio image and select it.

If you select Visual Studio Community (latest preview) on Windows Server:
1. You need a MSDN subscription
2. You are free to go with an Azure Pass

So scenario 2 is the way to go. Hope that helps for anyone having the same problem.

This issue is still closed and this repository is no longer maintained.

Marcel
