### ISSUE TITLE
Lab 7 documentation does not mention that you need to start the Storage Emulator

### ISSUE THREAD

**Issue by juunas11** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#38]
Both lab 7 documents fail to mention that the Storage Emulator needs to be started before running the data generation project.

**Comment by tjoudeh** [comment]
@juunas11 +1 this should be clearly documented to remove any ambiguity when following the Labs.

**Comment by seesharprun** [comment]
The commit seems to clarify this.

Closing the issue since it seems like it was resolved. Feel free to re-open if it is not.
