### ISSUE TITLE
Lab 2 answer key does not mention SQL 2012 LocalDB

### ISSUE THREAD

**Issue by juunas11** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#39]
The lab answer key for module 2 does not mention the installation requirement for SQL Server 2012 LocalDB. Since the projects' connection strings point to (localdb)\v11.0, they will not work without it.

**Comment by juunas11** [comment]
I've just noticed that lab 3 *does* mention it. So we could either remove the reference to SQL Local DB installation from module 2 lab or add it to the answer key, as it does not really make sense to only have it in one.

**Comment by seesharprun** [comment]
Closing the issue since it seems like it was resolved. Feel free to re-open if it is not.
