### ISSUE TITLE
Lab 8 Storage Account Bug

### ISSUE THREAD

**Issue by SidneyAndrewsMSFT** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#4]
From **Mats Johannesson** via http://borntolearn.mslearn.net.

Lab 8:

The first exercise is ok, no problems.

In the task Generate the Test Data
1.  On the Start screen, type Azure Storage Emulator.
2.  Click the Windows Azure Storage Emulator – v3.4 tile.
3.  Switch to Contoso.Events – Microsoft Visual Studio window.
4.  In the Solution Explorer pane, right-click the Contoso.Events.Data.Generation project, point to 
Debug, and then click Start New Instance

I have start the Windows Azure Storage when I run the Contoso.Events.Data.Generation it´s create a queue named signin not a blob with same name!

![fel](https://cloud.githubusercontent.com/assets/9090768/7682660/ade588c2-fd47-11e4-8e71-789b284a72c6.png)

**Comment by KindReality** [comment]
Is this still an issue? Thank you.

**Comment by mwasham** [comment]
no repro
