### ISSUE TITLE
Lab3: Empty database

### ISSUE THREAD

**Issue by guuskoning** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#40]
Locally I get an empty database but on Azure it works fine. I don't understand what I can do about it.

**Comment by guuskoning** [comment]
I saw in lab 4 a problem with the localization, I think I have the same problem.

**Comment by seesharprun** [comment]
Closing the issue since it seems like it was resolved. Feel free to re-open if it is not.
