### ISSUE TITLE
Lab 4 data generation project missing app setting

### ISSUE THREAD

**Issue by juunas11** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#41]
Module 4 lab data generation project does not have the new timeout app setting. This causes it to crash immediately.

We just need to an appSettings element in the data generation project's app.config, and add this inside it:

     <add key="Consoso.Events.Data.CommandTimeoutInSeconds" value="180" />

**Comment by seesharprun** [comment]
Closing the issue since it seems like it was resolved. Feel free to re-open if it is not.
