### ISSUE TITLE
Publishing to Azure not working

### ISSUE THREAD

**Issue by guuskoning** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#42]
I'm sorry but can't get it working. When I publish the cloud project to azure I don't get an error but the database seems empty (no tables created). When I try to run the app I get the following error:

"Unable to update database to match the current model because there are pending changes and automatic migration is disabled. Either write the pending model changes to a code-based migration or enable automatic migration. Set DbMigrationsConfiguration.AutomaticMigrationsEnabled to true to enable automatic migration."

I've tried to copy the seed function to a migration file, but that didn't make a difference.
Any suggestions?

**Comment by guuskoning** [comment]
I've copied the code from module 3 and used a dropCreateDatabaseAlways. With that code it works.

**Comment by seesharprun** [comment]
Do we need to do a PR to resolve this issue in the b-release branch? Let me know.
