### ISSUE TITLE
Lab7: Error on data generation

### ISSUE THREAD

**Issue by guuskoning** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#43]
When I try to debug the data.generation project I get an error on line 68:
var location = DbGeography.PointFromText(String.Format("POINT({0} {1})", latLong.Value, latLong.Key), 4326);

Error: An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll

Inner exception:
Message: {"24141: A number is expected at position 15 of the input. The input has ,69897."}
Source: "Microsoft.SqlServer.Types"

Maybe again something with my localization?

**Comment by guuskoning** [comment]
I have changed the  code to

String lon = latLong.Value.ToString(CultureInfo.InvariantCulture);
String lat = latLong.Key.ToString(CultureInfo.InvariantCulture);
var location = DbGeography.PointFromText(String.Format("POINT({0} {1})", lon, lat), DbGeography.DefaultCoordinateSystemId);

and the error is gone

**Comment by seesharprun** [comment]
In the c-release we just removed DbGeography all together and just went to distinct lat/long properties.

For the b-release, closing the issue since it seems like it was resolved. Feel free to re-open if it is not.
