### ISSUE TITLE
Lab 4 not working after deployment

### ISSUE THREAD

**Issue by davsebamse** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#5]
I get the following errors when deploying the service in lab 4: 

[SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.  This failure occurred while attempting to connect to the routing destination.]

I have checked that the connection string is set correctly, by creating a package and examine the files.

If I disabled the call to the database initializer will I instead get an error saying that it cannot find the microsoft.windowsazure.service.serviceruntime version 2.4.0.0, but I do not have any reference to that version in the projects.

**Comment by ElaMark** [comment]
Entity Framework 6 is the reason you're getting the issue. To get around the problem do 2 things:
1. Remove the ConnectionTimeout=30 from the database connection string.
2. Change the Constructor in the EventsContext.cs file as follows:

public EventsContext()
            : base("EventsContextConnectionString")
        {
            this.Database.CommandTimeout = 240;
        
        }

Mark

**Comment by SidneyAndrewsOpsgility** [comment]
I'm curious as i'm running through lab files now.  Is there a reason the ConnectionTimeout is specified in the constructor and not the connection string?  Though my (admittedly quick) internet search, I wasn't able to find a clear answer.

Thanks

**Comment by ElaMark** [comment]
Hi Sidney,

     The constructor specifies a **Command**Timeout rather than a **Connection**Timeout.

hth,
Mark

**Comment by davsebamse** [comment]
I have solved the problem using ```CreateDatabaseIfNotExists```

**Comment by davsebamse** [comment]
See #21
